"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { Activity, Cpu, Gauge, MemoryStick, Network, Users } from "lucide-react"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Card } from "@/components/ui/card"
import { calculateCounterRate, formatNetworkRate, type CounterSample } from "@/lib/network-units"

type Point={time:string;rx:number;tx:number;cpu:number|null;memory:number|null;subscribers:number;pppoe:number;ipoe:number}
type InterfaceRate={name:string;rx:number;tx:number}
const numberValue=(value:unknown)=>{const match=String(value??"").replaceAll(",","").match(/-?\d+(?:\.\d+)?/);return match?Number(match[0]):0}
const entries=(...sources:any[])=>sources.flatMap(source=>[...(source?.view?.items||[]),source?.view?.fields||{}]).flatMap(row=>Object.entries(row||{}).filter(([,value])=>value!==null&&value!==undefined&&value!=="").map(([key,value])=>({key:key.toLowerCase().replace(/[^a-z0-9%]+/g," ").trim(),value})))
const percent=(value:number)=>Math.max(0,Math.min(100,Math.round(value*10)/10))
const resourceMetrics=(snapshot:any)=>{const values=entries(snapshot?.system,snapshot?.health),find=(patterns:RegExp[])=>values.find(item=>patterns.some(pattern=>pattern.test(item.key))),cpu=values.find(item=>/\b(?:cpu|processor)\b/.test(item.key)&&/\b(?:load|usage|utilization|util|occupancy|used|percent|states)\b/.test(item.key)&&!/temperature|frequency|count|threshold/.test(item.key)),memoryPercent=values.find(item=>(/^(?:memory|mem)$/.test(item.key)||/\b(?:memory|mem)\b.*\b(?:usage|utilization|util|used percent|percent)\b/.test(item.key))&&(/%/.test(String(item.value))||/usage|utilization|util|percent/.test(item.key))),total=find([/^total memory$/,/^memory total$/,/^mem total$/]),free=find([/^free memory$/,/^memory free$/,/^mem free$/,/^available memory$/,/^memory available$/]),used=find([/^used memory$/,/^memory used$/,/^mem used$/]);let memory:number|null=null;if(memoryPercent)memory=percent(numberValue(memoryPercent.value));else if(total&&used&&numberValue(total.value)>0)memory=percent(numberValue(used.value)/numberValue(total.value)*100);else if(total&&free&&numberValue(total.value)>0)memory=percent((numberValue(total.value)-numberValue(free.value))/numberValue(total.value)*100);else{const linux=values.find(item=>/^memory .*total used free/.test(item.key)),numbers=String(linux?.value??"").replaceAll(",","").match(/\d+(?:\.\d+)?/g)?.map(Number)||[];if(numbers.length>=2&&numbers[0]>0)memory=percent(numbers[1]/numbers[0]*100);}return{cpu:cpu!==undefined?percent(numberValue(cpu.value)):null,memory}}
const rowValue=(row:any,patterns:RegExp[])=>{for(const[key,value]of Object.entries(row||{}))if(patterns.some(pattern=>pattern.test(key)))return numberValue(value);return 0}
const optionalRowValue=(row:any,patterns:RegExp[])=>{for(const[key,value]of Object.entries(row||{}))if(patterns.some(pattern=>pattern.test(key)))return numberValue(value);return null}
const rowName=(row:any,index:number)=>String(row.name??row.interface??row.port??row.portId??row[".id"]??`interface-${index+1}`)

export function DeviceLiveCharts({snapshot,lastUpdateAt,variant="default"}:{snapshot:any;lastUpdateAt?:string;variant?:"default"|"bng"}){
  const [history,setHistory]=useState<Point[]>([])
  const [rates,setRates]=useState<{rx:number;tx:number;top:InterfaceRate[]}>({rx:0,tx:0,top:[]})
  const previous=useRef<Map<string,{rx:CounterSample;tx:CounterSample}>>(new Map())
  const resources=useMemo(()=>resourceMetrics(snapshot),[snapshot])
  const subscriberMetrics=useMemo(()=>{const values=entries(snapshot?.subscribers,snapshot?.sessions),find=(patterns:RegExp[])=>values.find(item=>patterns.some(pattern=>pattern.test(item.key))),read=(patterns:RegExp[])=>numberValue(find(patterns)?.value),pppoe=read([/pppoe.*(?:session|active|total)/,/(?:session|active|total).*pppoe/]),ipoe=read([/ipoe.*(?:session|active|total)/,/(?:session|active|total).*ipoe/]),dhcp=read([/dhcp.*(?:session|lease|active|total)/,/(?:session|lease|active|total).*dhcp/]),active=read([/active.*(?:subscriber|session)/,/(?:subscriber|session).*active/,/^total.*sessions?$/])||pppoe+ipoe;return{active,pppoe,ipoe,dhcp}},[snapshot?.subscribers,snapshot?.sessions])
  useEffect(()=>{if(!lastUpdateAt)return;const telemetry=snapshot?.telemetry||snapshot?.interfaces,rows=telemetry?.view?.items||[],at=new Date(lastUpdateAt).getTime()||Date.now(),nextCounters=new Map<string,{rx:CounterSample;tx:CounterSample}>(),calculated:InterfaceRate[]=rows.map((row:any,index:number)=>{const name=rowName(row,index),rxBytes=rowValue(row,[/^rx.*bytes?$/i,/^receive.*bytes?$/i,/^in.*octets?$/i]),txBytes=rowValue(row,[/^tx.*bytes?$/i,/^transmit.*bytes?$/i,/^out.*octets?$/i]),speedBps=optionalRowValue(row,[/^speedbps$/i,/^speed.*bits/i]),uptimeSeconds=optionalRowValue(row,[/^uptime.*seconds/i]),rxSample:CounterSample={bytes:rxBytes,timestamp:at,interfaceId:name,speedBps,uptimeSeconds},txSample:CounterSample={bytes:txBytes,timestamp:at,interfaceId:name,speedBps,uptimeSeconds},before=previous.current.get(name),counterBits:32|64=rxBytes<=0xffffffff&&txBytes<=0xffffffff?32:64,reportedRx=optionalRowValue(row,[/rx.*bits.*(?:second|rate)/i,/receive.*bits.*(?:second|rate)/i,/input.*rate/i]),reportedTx=optionalRowValue(row,[/tx.*bits.*(?:second|rate)/i,/transmit.*bits.*(?:second|rate)/i,/output.*rate/i]),rx=reportedRx??calculateCounterRate(before?.rx,rxSample,{counterBits}).bps??0,tx=reportedTx??calculateCounterRate(before?.tx,txSample,{counterBits}).bps??0;nextCounters.set(name,{rx:rxSample,tx:txSample});return{name,rx,tx}});previous.current=nextCounters;const summary=telemetry?.view?.summary||telemetry?.summary||{},calculatedRx=calculated.reduce((sum,row)=>sum+row.rx,0),calculatedTx=calculated.reduce((sum,row)=>sum+row.tx,0),totals={rx:calculatedRx||numberValue(summary.rxBitsPerSecond),tx:calculatedTx||numberValue(summary.txBitsPerSecond),top:calculated.sort((a,b)=>b.rx+b.tx-a.rx-a.tx).slice(0,8)};setRates(totals);setHistory(current=>[...current,{time:new Date(lastUpdateAt).toLocaleTimeString([], {minute:"2-digit",second:"2-digit"}),rx:totals.rx,tx:totals.tx,...resources,...subscriberMetrics}].slice(-60))},[lastUpdateAt,snapshot?.telemetry,snapshot?.interfaces,resources,subscriberMetrics])
  const interfaces=snapshot?.interfaces?.view?.items||[],up=interfaces.filter((row:any)=>/^(up|running|online|true|yes)$/i.test(String(row.operState??row.state??row.running??row.link??""))).length,down=Math.max(0,interfaces.length-up),top=rates.top,metrics={...resources,rx:rates.rx,tx:rates.tx}
  if(variant==="bng")return <div className="grid gap-2 xl:grid-cols-12">
    <Card className="min-w-0 p-3 xl:col-span-4"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Activity className="size-3.5 text-violet-500"/>Live traffic throughput <span className="ml-auto font-mono text-[9px] text-muted-foreground">RX {formatNetworkRate(metrics.rx)} · TX {formatNetworkRate(metrics.tx)}</span></div><div className="h-48 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:480,height:192}}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" opacity={.18}/><XAxis dataKey="time" tick={{fontSize:8}}/><YAxis tickFormatter={formatNetworkRate} tick={{fontSize:8}} width={58}/><Tooltip formatter={(value:any)=>formatNetworkRate(Number(value))}/><Area type="monotone" dataKey="rx" stroke="#7c3aed" fill="#7c3aed" fillOpacity={.12} isAnimationActive={false}/><Area type="monotone" dataKey="tx" stroke="#3b82f6" fill="#3b82f6" fillOpacity={.08} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-4"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Users className="size-3.5 text-violet-500"/>Subscriber session trend <span className="ml-auto font-mono text-[9px] text-muted-foreground">{subscriberMetrics.active.toLocaleString()} active</span></div><div className="h-48 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:480,height:192}}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" opacity={.18}/><XAxis dataKey="time" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}} width={42}/><Tooltip/><Area type="monotone" dataKey="subscribers" stroke="#7c3aed" fill="#7c3aed" fillOpacity={.08} isAnimationActive={false}/><Area type="monotone" dataKey="pppoe" stroke="#3b82f6" fill="#3b82f6" fillOpacity={.05} isAnimationActive={false}/><Area type="monotone" dataKey="ipoe" stroke="#22c55e" fill="#22c55e" fillOpacity={.05} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-2"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Network className="size-3.5 text-emerald-500"/>Interface state</div><div className="h-44 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:220,height:176}}><PieChart><Pie data={[{name:"Up",value:up},{name:"Down",value:down}]} dataKey="value" nameKey="name" innerRadius={42} outerRadius={62} paddingAngle={2}><Cell fill="#22c55e"/><Cell fill="#ef4444"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="-mt-4 flex justify-center gap-3 text-[9px]"><span className="text-green-600">● {up} up</span><span className="text-red-600">● {down} down</span></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-2"><div className="mb-3 text-xs font-semibold">System resources</div><div className="space-y-3"><Metric icon={<Cpu className="size-4"/>} label="CPU usage" value={metrics.cpu===null?"—":`${metrics.cpu}%`} color="text-amber-500"/><Metric icon={<MemoryStick className="size-4"/>} label="Memory usage" value={metrics.memory===null?"—":`${metrics.memory}%`} color="text-violet-500"/></div><div className="mt-2 h-20 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:220,height:80}}><AreaChart data={history}><YAxis domain={[0,100]} hide/><Tooltip/><Area type="monotone" dataKey="cpu" stroke="#f59e0b" fill="#f59e0b" fillOpacity={.08} isAnimationActive={false}/><Area type="monotone" dataKey="memory" stroke="#7c3aed" fill="#7c3aed" fillOpacity={.08} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Card>
  </div>
  return <div className="grid gap-2 xl:grid-cols-12">
    <Card className="min-w-0 p-3 xl:col-span-6"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Activity className="size-3.5 text-blue-500"/>Live traffic <span className="ml-auto font-mono text-[10px] text-muted-foreground">RX {formatNetworkRate(metrics.rx)} · TX {formatNetworkRate(metrics.tx)}</span></div><div className="h-48 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:640,height:192}}><AreaChart data={history}><defs><linearGradient id="rxFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3b82f6" stopOpacity={.45}/><stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient><linearGradient id="txFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22c55e" stopOpacity={.4}/><stop offset="95%" stopColor="#22c55e" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={.2}/><XAxis dataKey="time" tick={{fontSize:9}}/><YAxis tickFormatter={formatNetworkRate} tick={{fontSize:9}} width={64}/><Tooltip formatter={(value:any)=>formatNetworkRate(Number(value))}/><Area type="monotone" dataKey="rx" stroke="#3b82f6" fill="url(#rxFill)" isAnimationActive={false}/><Area type="monotone" dataKey="tx" stroke="#22c55e" fill="url(#txFill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-3"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Network className="size-3.5 text-violet-500"/>Interface state</div><div className="h-48 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:280,height:192}}><PieChart><Pie data={[{name:"Up",value:up},{name:"Down",value:down}]} dataKey="value" nameKey="name" innerRadius={48} outerRadius={70} paddingAngle={3}><Cell fill="#22c55e"/><Cell fill="#ef4444"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="-mt-5 flex justify-center gap-4 text-[10px]"><span className="text-green-500">● {up} up</span><span className="text-red-500">● {down} down</span></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-3"><div className="grid grid-cols-2 gap-2"><Metric icon={<Cpu className="size-4"/>} label="CPU" value={metrics.cpu===null?"—":`${metrics.cpu}%`} color="text-amber-500"/><Metric icon={<MemoryStick className="size-4"/>} label="Memory" value={metrics.memory===null?"—":`${metrics.memory}%`} color="text-cyan-500"/></div><div className="mt-2 h-32 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:280,height:128}}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" opacity={.15}/><XAxis dataKey="time" hide/><YAxis domain={[0,100]} tick={{fontSize:8}} width={28}/><Tooltip formatter={(value:any,name:any)=>[value===null?"Unavailable":`${Number(value).toFixed(1)}%`,name]}/><Area type="monotone" dataKey="cpu" stroke="#f59e0b" fill="#f59e0b" fillOpacity={.12} dot={{r:2}} connectNulls={false} isAnimationActive={false}/><Area type="monotone" dataKey="memory" stroke="#06b6d4" fill="#06b6d4" fillOpacity={.12} dot={{r:2}} connectNulls={false} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><div className="flex justify-center gap-3 text-[9px]"><span className="text-amber-500">CPU</span><span className="text-cyan-500">Memory</span></div></Card>
    <Card className="min-w-0 p-3 xl:col-span-12"><div className="flex items-center gap-2 text-xs font-semibold"><Gauge className="size-3.5 text-fuchsia-500"/>Top interfaces</div><div className="mt-2 h-32 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:960,height:128}}><BarChart data={top} layout="vertical"><XAxis type="number" tickFormatter={formatNetworkRate} tick={{fontSize:8}}/><YAxis dataKey="name" type="category" width={110} tick={{fontSize:8}}/><Tooltip formatter={(value:any)=>formatNetworkRate(Number(value))}/><Bar dataKey="rx" stackId="rate" fill="#3b82f6"/><Bar dataKey="tx" stackId="rate" fill="#22c55e"/></BarChart></ResponsiveContainer></div></Card>
  </div>
}
function Metric({icon,label,value,color}:{icon:React.ReactNode;label:string;value:string;color:string}){return <div className="rounded-lg border bg-muted/20 p-2"><div className={`flex items-center gap-1 text-[10px] ${color}`}>{icon}{label}</div><div className="mt-1 font-mono text-base font-semibold">{value}</div></div>}
